### ISSUE TITLE
Valid configuration for windows

### ISSUE THREAD

**Issue by moreiraio** [jmederosalvarado/roslyn.nvim#28]
Hi,

sorry for the dumb question, but i'm trying to setup this on windows and i'm getting the following error:
Error executing Lua callback: .../Local/nvim-data/lazy/roslyn.nvim/lua/roslyn/install.lua:69: attempt to call field 'joinpath' (a nil value)
stack traceback:
        .../Local/nvim-data/lazy/roslyn.nvim/lua/roslyn/install.lua:69: in function 'install'
        ...ata/Local/nvim-data/lazy/roslyn.nvim/lua/roslyn/init.lua:153: in function <...ata/Local/nvim-data/lazy/roslyn.nvim/lua/roslyn/init.lua:152> 

Dows this work on windows?

**Comment by anden3** [comment]
You need nightly neovim, latest stable neovim doesn't contain everything that's needed, such as joinpath.

**Comment by moreiraio** [comment]
That solved the issue. Thanks.
