### ISSUE TITLE
CSInstallRoslyn fails when renaming directory

### ISSUE THREAD

**Issue by skogler** [jmederosalvarado/roslyn.nvim#3]
version: v0.10.0-dev-366d0c7

I have this odd issue that `vim.fn.rename` fails to move the dir from `/tmp` to `~/.local/share/nvim`:

   E210: Error reading "/tmp/nvim.skogler/aMGWsJ/3/out/microsoft.codeanalysis.languageserver.linux-x64/4.8.0-3.23475.7/content/LanguageServer/linux-x64

It creates a 0 byte file called roslyn in the target directory, so I assume it has something to do with it not realizing this is a directory.
   
I can reproduce this by calling the lua function directly, and I tried different combinations with trailing slashes to fix it, but so far nothing worked.

**Comment by jmederosalvarado** [comment]
If you can reproduce it outside of plugin context I would suggest opening an issue in the neovim repo. Closing this.

On a side note: I'm planning to migrate installation to [`mason.nvim`](https://github.com/williamboman/mason.nvim), I might leave the current `CSInstallRoslyn` as fallback though.

**Comment by skogler** [comment]
Makes sense, thanks for the awesome work! Would love the mason install method, since I use it anyways.
